name: CI/CD Build and Deploy to On-Premise K8s

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend # Đường dẫn tới thư mục chứa Dockerfile Backend (Bạn tự chỉnh lại cho đúng cấu trúc repo của bạn nhé)
        file: ./backend/Dockerfile
        push: true
        tags: hoangvu3134/fly-backend:latest

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend # Đường dẫn tới thư mục chứa Dockerfile Frontend
        file: ./frontend/Dockerfile
        push: true
        tags: hoangvu3134/fly-frontend:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: k8s-runner 
    steps:
    - name: Deploy to Cluster
      run: |
        kubectl apply -f $HOME/k8s-manifests/apps.yaml
        kubectl apply -f $HOME/k8s-manifests/ingress.yaml
        
    - name: Rollout Restart Deployment (Để K8s cập nhật Image mới nhất ngay lập tức)
      run: |
        kubectl rollout restart deployment fly-backend
        kubectl rollout restart deployment fly-frontend